CREATE TABLE IF NOT EXISTS quiz_games (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pin VARCHAR(8) NOT NULL UNIQUE,
  status ENUM('lobby','playing','finished') NOT NULL DEFAULT 'lobby',
  current_question INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quiz_players (
  id INT AUTO_INCREMENT PRIMARY KEY,
  game_pin VARCHAR(8) NOT NULL,
  name VARCHAR(64) NOT NULL,
  last_active TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (game_pin),
  FOREIGN KEY (game_pin) REFERENCES quiz_games(pin) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
